name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL2
      run: sudo apt-get install libsdl2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - name: Run integration tests
      run: cargo run -- --headless test_data/core_words.fr4
      
